name: CI

on: [gollum]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        commit_message: Apply automatic changes
